#!/usr/bin/env bash
echo "Bootstrapping..."
declare -A linux_types 

if [ -e /etc/os-release ] ; then 
  source /etc/os-release
fi

function install_redhat_like() {
  sudo yum install -y vim tmux 
  # install starship
  curl -sS https://starship.rs/install.sh | sh -s -- -f --bin-dir $HOME/bin
  # install tmux plugin manager
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  # install direnv - critical 
  bin_path=$HOME/bin
  curl -sfL https://direnv.net/install.sh | bash
  echo "Doing redhat like install"
}

function install_debian_like() {
  echo "Installing ubuntu like"
}

echo "id: $ID" 
case "$ID" in 
  "almalinux" |"redhat" | "rhel" )
    install_redhat_like ;;
  "Ubuntu")
    install_debian_like ;;
  *)
  echo "Unable to determin install type"
esac



