#!/usr/bin/env bash
echo "Bootstrapping..."
declare -A linux_types 

if [ -e /etc/os-release ] ; then 
  source /etc/os-release
fi

function install_redhat_like() {
  yum install -y vim tmux 
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tmux new-session -s tmux  "~/.tmux/plugins/tpm/tpm && ~/.tmux/plugins/tpm/bin/install_plugins"
  echo "Doing redhat like install"
}

function install_debian_like() {
  echo "Installing ubuntu like"
}

echo "id: $ID" 
case "$ID" in 
  "almalinux" |"redhat" | "rhel" )
    install_redhat_like ;;
  "Ubuntu")
    install_debian_like ;;
  *)
  echo "Unable to determin install type"
esac



