#!/usr/bin/env bash
echo "Bootstrapping..."
declare -A linux_types 

if [ -e /etc/os-release ] ; then 
  source /etc/os-release
fi

function install_redhat_like() {
  sudo yum install -y vim tmux unzip direnv
  # install starship
  curl -sS https://starship.rs/install.sh | sh -s -- -f --bin-dir $HOME/bin
  # install tmux plugin manager
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  # install direnv - critical 
  bin_path=$HOME/bin
  curl -sfL https://direnv.net/install.sh | bash
  # eget 
  curl -o eget.sh https://zyedidia.github.io/eget.sh
  bash eget.sh
  mv ./eget ~/bin
  # now we have eget, lets install some other bits we'll likely need
  ~/bin/eget --to=~/bin junegunn/fzf
  echo "Doing redhat like install"
  source ~/.bashrc
}

function install_debian_like() {
  echo "Installing ubuntu like"
  curl -o eget.sh https://zyedidia.github.io/eget.sh
  wget https://github.com/zyedidia/eget/releases/download/v1.3.4/eget-1.3.4-linux_amd64.tar.gz -O eget.tgz
  tar -xzvf eget.tgz eget-1.3.4-linux_amd64/eget --strip-components=1 
  mv ./eget ~/bin
  # now we have eget, lets install some other bits we'll likely need
  ~/bin/eget --to=~/bin junegunn/fzf 
  ~/bin/eget --to=~/bin 99designs/aws-vault
  sudo apt-get install tmux tmux-plugin-manager eza cron jq
  # aws cli installation
  ( 
  
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

}

echo "id: $ID" 
case "$ID" in 
  "almalinux" |"redhat" | "rhel" )
    install_redhat_like ;;
  "Ubuntu" | "ubuntu")
    install_debian_like ;;
  *)
  echo "Unable to determin install type for $ID"
esac



